#include <bits/stdc++.h>
using namespace std;
struct Perm{array<unsigned char,5>p,inv;};struct Base{int n;vector<vector<int>>a;vector<pair<int,int>>E;vector<int>eid;};
Base rd(string path){ifstream in(path);vector<vector<int>>m;string l;while(getline(in,l)){if(l.empty())continue;stringstream ss(l);vector<int>r;int x;while(ss>>x)r.push_back(x);if(!r.empty())m.push_back(r);}int n=m.size();Base b{n,vector<vector<int>>(n),{},vector<int>(n*n,-1)};for(int i=0;i<n;i++)for(int j=i+1;j<n;j++)if(m[i][j]){int e=b.E.size();b.E.push_back({i,j});b.eid[i*n+j]=b.eid[j*n+i]=e;b.a[i].push_back(j);b.a[j].push_back(i);}return b;}
vector<vector<int>>cycles(const Base&b,int L){vector<vector<int>>o;for(int s=0;s<b.n;s++){vector<int>p{s};uint64_t seen=1ULL<<s;function<void(int)>dfs=[&](int u){if((int)p.size()==L){if(find(b.a[u].begin(),b.a[u].end(),s)!=b.a[u].end()&&p[1]<p.back())o.push_back(p);return;}for(int v:b.a[u])if(v>s&&!(seen>>v&1ULL)){seen|=1ULL<<v;p.push_back(v);dfs(v);p.pop_back();seen&=~(1ULL<<v);}};for(int v:b.a[s])if(v>s){seen|=1ULL<<v;p.push_back(v);dfs(v);p.pop_back();seen&=~(1ULL<<v);}}return o;}
bool is5(const array<unsigned char,5>&p){int x=0;for(int k=1;k<=5;k++){x=p[x];if(x==0)return k==5;}return false;}
struct C{vector<int>w,vars;int type=0,sh=0;};
int main(int ac,char**av){if(ac<4){cerr<<"base cuts warm [seed]\n";return 2;}uint64_t seed=ac>4?stoull(av[4]):123;Base b=rd(av[1]);vector<Perm>G;array<unsigned char,5>a={0,1,2,3,4};do{int iv=0;for(int i=0;i<5;i++)for(int j=i+1;j<5;j++)iv+=a[i]>a[j];if(!(iv&1)){Perm q;q.p=a;for(int i=0;i<5;i++)q.inv[q.p[i]]=i;G.push_back(q);}}while(next_permutation(a.begin(),a.end()));vector<int>pa(b.n,-1),pe(b.n,-1);queue<int>qq;pa[0]=0;qq.push(0);while(!qq.empty()){int u=qq.front();qq.pop();for(int v:b.a[u])if(pa[v]<0){pa[v]=u;pe[v]=b.eid[u*b.n+v];qq.push(v);}}vector<int>vo(b.E.size(),-1),cot;for(int e=0;e<(int)b.E.size();e++){bool tr=0;for(int v=1;v<b.n;v++)if(pe[v]==e)tr=1;if(!tr){vo[e]=cot.size();cot.push_back(e);}}int r=cot.size();auto word=[&](const vector<int>&p){vector<int>w;for(int i=0;i<(int)p.size();i++){int u=p[i],v=p[(i+1)%p.size()],z=vo[b.eid[u*b.n+v]];if(z>=0)w.push_back((u<v?1:-1)*(z+1));}return w;};vector<C>CS;for(auto&p:cycles(b,16)){C c;c.w=word(p);for(int z:c.w)c.vars.push_back(abs(z)-1);sort(c.vars.begin(),c.vars.end());c.vars.erase(unique(c.vars.begin(),c.vars.end()),c.vars.end());CS.push_back(c);}ifstream cf(av[2]);string line;while(getline(cf,line)){if(line.empty())continue;stringstream ss(line);C c;c.type=1;ss>>c.sh;int z;while(ss>>z)c.w.push_back(z);for(int q:c.w)c.vars.push_back(abs(q)-1);sort(c.vars.begin(),c.vars.end());c.vars.erase(unique(c.vars.begin(),c.vars.end()),c.vars.end());CS.push_back(c);}auto prod=[&](const C&c,const vector<int>&x){array<unsigned char,5>cur={0,1,2,3,4},nxt;for(int zz:c.w){int z=abs(zz)-1;auto&p=zz>0?G[x[z]].p:G[x[z]].inv;for(int s=0;s<5;s++)nxt[s]=p[cur[s]];cur=nxt;}return cur;};auto good=[&](const C&c,const vector<int>&x){auto p=prod(c,x);return c.type? p[c.sh]!=c.sh:is5(p);};vector<vector<int>>inc(r);for(int i=0;i<(int)CS.size();i++)for(int v:CS[i].vars)inc[v].push_back(i);vector<int>warm(r,-1);ifstream wi(av[3]);while(getline(wi,line)){if(line.empty()||line.rfind("FOUND",0)==0)continue;stringstream ss(line);int u,v;ss>>u>>v;array<unsigned char,5>p;for(int k=0;k<5;k++){int z;ss>>z;p[k]=z;}int var=vo[b.eid[u*b.n+v]];if(var>=0)for(int g=0;g<(int)G.size();g++)if(G[g].p==p)warm[var]=g;}mt19937_64 R(seed);int global=CS.size();vector<int>globalx;
 for(int rr=0;rr<10000;rr++){vector<int>x;if(rr==0&&find(warm.begin(),warm.end(),-1)==warm.end())x=warm;else{x.assign(r,0);for(int&i:x)i=R()%G.size();}vector<char>ok(CS.size());vector<int>wt(CS.size(),1);int bad=0,cost=0;for(int i=0;i<(int)CS.size();i++){ok[i]=good(CS[i],x);bad+=!ok[i];cost+=!ok[i]*wt[i];}int stall=0;for(int st=0;st<200000;st++){if(bad<global){global=bad;globalx=x;cerr<<"BEST rr="<<rr<<" st="<<st<<" bad="<<bad<<" cost="<<cost<<"\n";}if(!bad){cout<<"FOUND\n";for(int i=0;i<r;i++){auto[u,v]=b.E[cot[i]];cout<<u<<" "<<v;for(int s=0;s<5;s++)cout<<" "<<(int)G[x[i]].p[s];cout<<"\n";}return 0;}vector<int>bs;long long tw=0;for(int i=0;i<(int)CS.size();i++)if(!ok[i]){bs.push_back(i);tw+=wt[i];}long long pick=R()%tw;int ci=bs[0];for(int j:bs){if(pick<wt[j]){ci=j;break;}pick-=wt[j];}int bestc=INT_MAX,bv=-1,bz=-1;vector<pair<int,int>>ties;for(int v:CS[ci].vars){int old=x[v];int oldpart=0;for(int cj:inc[v])oldpart+=!ok[cj]*wt[cj];for(int z=0;z<(int)G.size();z++){x[v]=z;int nc=cost-oldpart;for(int cj:inc[v])nc+=!good(CS[cj],x)*wt[cj];if(nc<bestc){bestc=nc;ties={{v,z}};}else if(nc==bestc)ties.push_back({v,z});}x[v]=old;}auto [v,z]=ties[R()%ties.size()];int old=x[v]; int oldcost=cost; x[v]=z;cost=0;bad=0;for(int i=0;i<(int)CS.size();i++){ok[i]=good(CS[i],x);bad+=!ok[i];cost+=!ok[i]*wt[i];}if(cost>=oldcost)stall++;else stall=0;(void)old;
 if(stall>=25){for(int i=0;i<(int)CS.size();i++)if(!ok[i])wt[i]++;cost=0;for(int i=0;i<(int)CS.size();i++)cost+=!ok[i]*wt[i];stall=0;}
 if(st%5000==4999){for(int&i:wt)i=max(1,(i+1)/2);cost=0;for(int i=0;i<(int)CS.size();i++)cost+=!ok[i]*wt[i];}
 }}cerr<<"NONE best="<<global<<"\n";if(!globalx.empty()){ofstream o("/mnt/data/a5_breakout_best.txt");for(int z:globalx)o<<z<<" ";o<<"\n";}return 1;}
