#include <bits/stdc++.h>
using namespace std;
constexpr int N=38,MAXE=768,SHIFT=10;
struct KeyHash{size_t operator()(uint64_t x)const noexcept{x^=x>>33;x*=0xff51afd7ed558ccdULL;x^=x>>33;x*=0xc4ceb9fe1a85ec53ULL;x^=x>>33;return x;}};
vector<int> lens,compOf(N),posOf(N),startv;uint64_t baseAdj[N];bool baseE[N][N];
vector<pair<int,int>>E;int eid[N][N],pid[MAXE][MAXE];vector<int>incV[N];
unordered_set<uint64_t,KeyHash>S2,S3,S4;vector<bitset<MAXE>>pairbad,ban3;vector<vector<int>>qadj;
int pathv[9];uint64_t usedMask;long long genNodes;
inline uint64_t enc2(int a,int b){if(a>b)swap(a,b);return ((uint64_t)a<<SHIFT)|b;}
inline uint64_t enc3(int a,int b,int c){int z[3]={a,b,c};sort(z,z+3);return ((uint64_t)z[0]<<(2*SHIFT))|((uint64_t)z[1]<<SHIFT)|z[2];}
inline uint64_t enc4(int a,int b,int c,int d){int z[4]={a,b,c,d};sort(z,z+4);return ((uint64_t)z[0]<<(3*SHIFT))|((uint64_t)z[1]<<(2*SHIFT))|((uint64_t)z[2]<<SHIFT)|z[3];}
void addClause(vector<int>z){sort(z.begin(),z.end());z.erase(unique(z.begin(),z.end()),z.end());if(z.size()==2)S2.insert(enc2(z[0],z[1]));else if(z.size()==3)S3.insert(enc3(z[0],z[1],z[2]));else if(z.size()==4)S4.insert(enc4(z[0],z[1],z[2],z[3]));}
void genDfs(int s,int cur,int dep,int L,bool pm,vector<int>&me){genNodes++;if(dep==L){bool b=baseE[cur][s];int ee=eid[cur][s];if(!b&&ee<0)return;bool lm=!b;if(pm&&lm)return;bool fm=!baseE[s][pathv[1]];if(fm&&lm)return;auto z=me;if(lm)z.push_back(ee);if(z.empty()||z.size()>4)return;addClause(move(z));return;}uint64_t c=baseAdj[cur]&~usedMask;while(c){int w=__builtin_ctzll(c);c&=c-1;if(w<=s)continue;pathv[dep]=w;usedMask|=1ULL<<w;genDfs(s,w,dep+1,L,false,me);usedMask&=~(1ULL<<w);}if(!pm)for(int w=s+1;w<N;w++)if(!(usedMask>>w&1)&&eid[cur][w]>=0){pathv[dep]=w;usedMask|=1ULL<<w;me.push_back(eid[cur][w]);genDfs(s,w,dep+1,L,true,me);me.pop_back();usedMask&=~(1ULL<<w);}}
bitset<MAXE>selected;vector<int>sel;uint64_t matched,adjm[N];int matev[N],qrem[8][8],K;uint64_t posmask[8];bool reflfixed[8];long long nodes,leaves,cpr,p16pr;double limitSec=600;chrono::steady_clock::time_point st;
inline bool pathrec(int cur,int target,int rem,uint64_t vis){if(rem==0)return cur==target;if(cur==target)return false;uint64_t c=adjm[cur]&~vis;while(c){int w=__builtin_ctzll(c);c&=c-1;if(rem==1&&w!=target)continue;if(rem>1&&w==target)continue;if(pathrec(w,target,rem-1,vis|(1ULL<<w)))return true;}return false;}
inline bool clausebad(int e){if((pairbad[e]&selected).any())return true;int d=sel.size();for(int ii=0;ii<d;ii++){int f=sel[ii],P=pid[e][f];if((ban3[P]&selected).any())return true;auto const&A=qadj[P];if(A.empty())continue;for(int jj=0;jj<d;jj++)if(jj!=ii)for(int kk=jj+1;kk<d;kk++)if(kk!=ii){int Q=pid[sel[jj]][sel[kk]];if(binary_search(A.begin(),A.end(),Q))return true;}}return false;}
inline bool qavail(int e){auto[u,v]=E[e];int a=compOf[u],b=compOf[v];return a==b?qrem[a][a]>0:qrem[a][b]>0;}
inline void qupd(int e,int d){auto[u,v]=E[e];int a=compOf[u],b=compOf[v];if(a==b)qrem[a][a]+=d;else qrem[a][b]+=d,qrem[b][a]+=d;}

bool lexMaskLE(uint64_t a,uint64_t b,int L,int &cmp){
 vector<int>A,B;for(int p=0;p<L;p++){if(a>>p&1)A.push_back(p);if(b>>p&1)B.push_back(p);}cmp=(A<B?-1:(B<A?1:0));return cmp<=0;
}
bool symCandidate(int e,uint64_t newmask[8],bool newref[8]){
 for(int c=0;c<K;c++){newmask[c]=posmask[c];newref[c]=reflfixed[c];}
 return true;
}

inline bool valid(int e){auto[u,v]=E[e];if((matched>>u&1)||(matched>>v&1)||!qavail(e))return false;if(clausebad(e)){cpr++;return false;}if(pathrec(u,v,15,1ULL<<u)){p16pr++;return false;}return true;}
bool quotaFeasible(){int freec[8]{};for(int u=0;u<N;u++)if(!(matched>>u&1))freec[compOf[u]]++;for(int i=0;i<K;i++){int need=2*qrem[i][i];for(int j=0;j<K;j++)if(j!=i)need+=qrem[i][j];if(need!=freec[i])return false;if(2*qrem[i][i]>freec[i])return false;for(int j=i+1;j<K;j++)if(qrem[i][j]>min(freec[i],freec[j]))return false;}return true;}
bool dfs(){nodes++;if((nodes&((1<<18)-1))==0){double t=chrono::duration<double>(chrono::steady_clock::now()-st).count();if(t>limitSec)throw runtime_error("TIME");}if(!quotaFeasible())return false;if(__builtin_popcountll(matched)==N){leaves++;return true;}int bu=-1;vector<int>bc;for(int u=0;u<N;u++)if(!(matched>>u&1)){vector<int>c;for(int e:incV[u])if(valid(e))c.push_back(e);if(c.empty())return false;if(bu<0||c.size()<bc.size()){bu=u;bc=move(c);if(bc.size()==1)break;}}for(int e:bc){if(!valid(e))continue;uint64_t nm[8];bool nr[8];if(!symCandidate(e,nm,nr))continue;auto[u,v]=E[e];uint64_t om[8];bool orf[8];for(int c=0;c<K;c++){om[c]=posmask[c];orf[c]=reflfixed[c];posmask[c]=nm[c];reflfixed[c]=nr[c];}matched|=(1ULL<<u)|(1ULL<<v);selected.set(e);sel.push_back(e);adjm[u]|=1ULL<<v;adjm[v]|=1ULL<<u;qupd(e,-1);if(dfs())return true;qupd(e,1);adjm[u]&=~(1ULL<<v);adjm[v]&=~(1ULL<<u);sel.pop_back();selected.reset(e);matched&=~((1ULL<<u)|(1ULL<<v));for(int c=0;c<K;c++){posmask[c]=om[c];reflfixed[c]=orf[c];}}return false;}
void initSearch(int Q[8][8]){memcpy(qrem,Q,sizeof(qrem));matched=0;selected.reset();sel.clear();nodes=leaves=cpr=p16pr=0;fill(matev,matev+N,-1);fill(posmask,posmask+8,0);fill(reflfixed,reflfixed+8,false);for(int i=0;i<N;i++)adjm[i]=baseAdj[i];}
bool solveQ(int Q[8][8]){int b=-1;for(int j=1;j<K;j++)if(Q[0][j]){b=j;break;}if(b<0)return false;initSearch(Q);int u=startv[0],v=startv[b],e=eid[u][v];if(e<0||!qavail(e))return false;matched=(1ULL<<u)|(1ULL<<v);selected.set(e);sel.push_back(e);adjm[u]|=1ULL<<v;adjm[v]|=1ULL<<u;qupd(e,-1);posmask[0]|=1ULL<<posOf[u];posmask[b]|=1ULL<<posOf[v];st=chrono::steady_clock::now();return dfs();}
int main(int argc,char**argv){if(argc<2)return 2;if(argc>2)limitSec=stod(argv[2]);ifstream in(argv[1]);in>>K;lens.resize(K);for(int&i:lens)in>>i;if(accumulate(lens.begin(),lens.end(),0)!=N)return 2;memset(eid,-1,sizeof(eid));int off=0;set<int>forb={4,8,16,32};for(int c=0;c<K;c++){startv.push_back(off);for(int p=0;p<lens[c];p++){int u=off+p,v=off+(p+1)%lens[c];compOf[u]=c;posOf[u]=p;baseE[u][v]=baseE[v][u]=1;baseAdj[u]|=1ULL<<v;baseAdj[v]|=1ULL<<u;}off+=lens[c];}for(int u=0;u<N;u++)for(int v=u+1;v<N;v++)if(!baseE[u][v]){bool ok=true;if(compOf[u]==compOf[v]){int L=lens[compOf[u]],d=abs(posOf[u]-posOf[v]);d=min(d,L-d);if(forb.count(d+1)||forb.count(L-d+1))ok=false;}if(ok){eid[u][v]=eid[v][u]=E.size();E.push_back({u,v});incV[u].push_back(E.size()-1);incV[v].push_back(E.size()-1);}}for(int L:{4,8})for(int s=0;s<N;s++){pathv[0]=s;usedMask=1ULL<<s;vector<int>me;genDfs(s,s,1,L,false,me);}int M=E.size(),pc=0;for(int i=0;i<M;i++)for(int j=i+1;j<M;j++)pid[i][j]=pid[j][i]=pc++;pairbad.resize(M);ban3.resize(pc);qadj.resize(pc);for(auto k:S2){int b=k&1023,a=k>>SHIFT;pairbad[a].set(b);pairbad[b].set(a);}for(auto k:S3){int c=k&1023,b=(k>>SHIFT)&1023,a=k>>(2*SHIFT);ban3[pid[a][b]].set(c);ban3[pid[a][c]].set(b);ban3[pid[b][c]].set(a);}for(auto k:S4){int d=k&1023,c=(k>>SHIFT)&1023,b=(k>>(2*SHIFT))&1023,a=k>>(3*SHIFT);int P[3][2]={{pid[a][b],pid[c][d]},{pid[a][c],pid[b][d]},{pid[a][d],pid[b][c]}};for(auto&x:P){qadj[x[0]].push_back(x[1]);qadj[x[1]].push_back(x[0]);}}for(auto&v:qadj){sort(v.begin(),v.end());v.erase(unique(v.begin(),v.end()),v.end());}
 long long rows=0,total=0,totleaf=0;int Q[8][8];while(true){memset(Q,0,sizeof(Q));bool ok=true;for(int i=0;i<K;i++)for(int j=i;j<K;j++){int x;if(!(in>>x)){ok=false;break;}Q[i][j]=Q[j][i]=x;}if(!ok)break;rows++;bool f=false;try{f=solveQ(Q);}catch(...){cerr<<"TIME row="<<rows<<" nodes="<<nodes<<"\n";return 3;}total+=nodes;totleaf+=leaves;if(f){cerr<<"FEASIBLE row="<<rows<<" nodes="<<nodes<<" leaves="<<leaves<<"\n";return 1;}if(rows%25==0)cerr<<"PROGRESS rows="<<rows<<" total="<<total<<"\n";}cerr<<"SUMMARY rows="<<rows<<" feasible=0 nodes="<<total<<" leaves="<<totleaf<<"\n";return 0;}
